language: python
cache: pip
python:
  - 3.7


install:
  - pip install pipenv
  - pipenv install


jobs:
  include:
    - stage: test
      script:
        - coverage run --source='.' -m pytest
        - coverage report -m
        - coveralls
    - stage: deploy
      script:
        - echo 'Run deploy'

stages:
  - name: test
  - name: deploy
    if: type = push AND branch = master
